### ISSUE TITLE
Get-MVPProfile works only with -ID parameter

### ISSUE THREAD

**Issue by RStadlmair** [lazywinadmin/MVP#10]
Hi Lazyadmin !

Just experimenting with your Module. 
Get-MVPProfile (and also)
Get-MVPContribution without any parameter returns :

_WARNUNG: Failed to invoke the GetOnlineIdentities API because Der Remoteserver hat einen Fehler zurückgegeben: (400)
Ungültige Anforderung._

I did set the Key correctly and also have values in the variables:
MVPAuthorizationCode
MVPOauth2
MVPPrimaryKey

Any ideas ?

R.

**Comment by lazywinadmin** [comment]
Hi @RStadlmair , thanks for the feedback
Did you run ```Set-MVPConfiguration``` first ?

**Comment by RStadlmair** [comment]
Hi Francois !

I did set Set-MVPConfiguration and it worked. Also Get-MVPProfile delivers values, i.e.

```
(Get-MVPProfile -ID 5002215).Headline
```
results in
```
www.powershell.co.at
```

Get-MVPContributionType works
Get-MVPContributionArea Errors

Regards/Roman

**Comment by lazywinadmin** [comment]
Hi Roman,

I'm not able to reproduce the errors you are getting.

Which version of PowerShell are you using ?
Did you install from the PowerShell Gallery ?
Also if it is possible for you, are you able to reproduce the error on different machines ?

On my end I'm able to query

```Get-MVPProfile```

```
PS C:\> Get-MVPProfile


Metadata             : @{PageTitle=Francois-Xavier Cat is a Microsoft MVP in PowerShell who has been in the IT field
                       since 2007. He is currently an Automation Specialist in a large Financial company.;
                       TemplateName=; Keywords=; Description=}
MvpId                : 5000475
YearsAsMvp           : 4
FirstAwardYear       : 2014
AwardCategoryDisplay : Cloud and Datacenter Management
TechnicalExpertise   :
InTheSpotlight       : False
...

```

```Get-MVPContributionArea```

```
AwardName                       ContributionArea
---------                       ----------------
Cloud and Datacenter Management {@{Id=b003f4ef-066b-e511-810c-fc35b428ced0; Name

```




cc: @p0w3rsh3ll

**Comment by RStadlmair** [comment]
Hi!



I guess i found the issue, by debugging Get-MVPContribution.

 

It uses the wrong live-ID to access the data and produced an error.

 

Will find my way through, Thanks for your help anyway.

 

Regards/Roman

 

 

Von: François-Xavier Cat [mailto:notifications@github.com] 
Gesendet: Thursday, May 18, 2017 5:34 AM
An: lazywinadmin/MVP <MVP@noreply.github.com>
Cc: Roman Stadlmair <rs@rconsult.at>; Mention <mention@noreply.github.com>
Betreff: Re: [lazywinadmin/MVP] Get-MVPProfile works only with -ID parameter (#10)

 

Hi Roman,

I'm not able to reproduce the errors you are getting.

Which version of PowerShell are you using ?
Did you install from the PowerShell Gallery ?
Also if it is possible for you, are you able to reproduce the error on different machines ?

On my end I'm able to query

Get-MVPProfile

PS C:\> Get-MVPProfile
 
 
Metadata             : @{PageTitle=Francois-Xavier Cat is a Microsoft MVP in PowerShell who has been in the IT field
                       since 2007. He is currently an Automation Specialist in a large Financial company.;
                       TemplateName=; Keywords=; Description=}
MvpId                : 5000475
YearsAsMvp           : 4
FirstAwardYear       : 2014
AwardCategoryDisplay : Cloud and Datacenter Management
TechnicalExpertise   :
InTheSpotlight       : False
...
 

Get-MVPContributionArea

AwardName                       ContributionArea
---------                       ----------------
Cloud and Datacenter Management {@{Id=b003f4ef-066b-e511-810c-fc35b428ced0; Name
 

cc: @p0w3rsh3ll <https://github.com/p0w3rsh3ll>

**Comment by lazywinadmin** [comment]
Thanks for the feedback.
