### ISSUE TITLE
Subscriber Key doesn't persist

### ISSUE THREAD

**Issue by jdhitsolutions** [lazywinadmin/MVP#11]
Every time I try to use a command in the module in a new PowerShell session I get prompted to run Set-MVPConfiguration to set the primary key.  I can do that and everything works. Until the next PowerShell session. Is there a better way to persist this information?

Running PowerShell 5.1.16193.1001

**Comment by jdhitsolutions** [comment]
Or perhaps I'm suppose to set that in my profile?

**Comment by lazywinadmin** [comment]
Good suggestion, I guess storing it in the profile make sense.
i'll add this into the help.

Thanks @jdhitsolutions

**Comment by lazywinadmin** [comment]
Added here: https://github.com/lazywinadmin/MVP#PersistentSubscriptionKey
