### ISSUE TITLE
Module commands not autoloading

### ISSUE THREAD

**Issue by jdhitsolutions** [lazywinadmin/MVP#12]
This one is puzzling. The module is installed under C:\program files

C:\Program Files\WindowsPowerShell\Modules\mvp\0.0.1.0\MVP.psm1

So it should autoload the commands. Yet I have to import the module first.

![image](https://cloud.githubusercontent.com/assets/12089920/26213419/f768a1cc-3bc6-11e7-9507-3467e3cec907.png)

Once the module is loaded Get-Command -module mvp shows me everything.

**Comment by lazywinadmin** [comment]
Thanks @jdhitsolutions this appears to be fixed with the issues your reported in #13 
Thanks again. Will commit soon.
