### ISSUE TITLE
Module Manifest suggestions

### ISSUE THREAD

**Issue by jdhitsolutions** [lazywinadmin/MVP#13]
Here are some thoughts and suggestions on the module manifest:

- Is PowerShell v3 truly the minimum required version?
- The recommended best practice is not to use * for functions to export and instead explicitly list each one. 
- I think it is also a good practice to not export cmdlets or variables in the manifest unless you really are.

**Comment by lazywinadmin** [comment]
Thanks @jdhitsolutions 
Yes I'm using Invoke-RestMethod which is available only from PS3
I updated the manifest with your recommendations.

Thanks again, appreciated! Will commit soon.
