### ISSUE TITLE
Cannot clear the oAuth for wrong email

### ISSUE THREAD

**Issue by wsmelton** [lazywinadmin/MVP#17]
For the life of me I cannot get this to clear and even on a separate machine I get the same result...

Trying to set the MVP profile I have the API key all setup and using the one associated with my email for the MVP profile (outlook.com), but the oAuth window is pulling in my gmail account for some reason:
![image](https://user-images.githubusercontent.com/11204251/39688693-88835eac-5199-11e8-8bb4-3271cdd487bc.png)

Any idea how to clear that credential cache...or if there is one? I have searched around but cannot find anything that shows it is associated  (e.g. cookies cleared, browser cache cleared, checked app auth for my Live ID).

**Comment by wsmelton** [comment]
Ah, never mind. Finally figured it out...had to go into Internet Settings from Windows Settings and clear everything there...finally prompted to provide login credentials after that for the oAuth prompt.

**Comment by lazywinadmin** [comment]
Thanks for your comment @wsmelton 
I'll add something in the documentation for that 👍
