### ISSUE TITLE
New Feature - Test-MVPContribution

### ISSUE THREAD

**Issue by lazywinadmin** [lazywinadmin/MVP#21]
Checks if entry exists online, wrapper around Get-MVPContribution based on Date, Title, Type, Techno, Link
Could also check if the information provided are correct

**Comment by Windos** [comment]
For those that can't query the API themselves, is it possible to get and example of the JSON/object returned from "https://mvpapi.azure-api.net/mvp/api/contributions/0/1"

Given that, it should be possible to wire up a working function (despite not being able to test it lol.)

**Comment by lazywinadmin** [comment]
Hi @Windos ! thanks for looking at this 😃 
I added some output examples here: https://github.com/lazywinadmin/MVP/tree/master/Examples/output

Hope this helps!
