### ISSUE TITLE
New Function - Show MVP Profile in browser

### ISSUE THREAD

**Issue by lazywinadmin** [lazywinadmin/MVP#27]
Add a function to show the MVP profile in the default browser.
`Show-MVPProfile` ?

URL example:
`https://mvp.microsoft.com/en-us/PublicProfile/<MVPID>`

For example mine is: `https://mvp.microsoft.com/en-us/PublicProfile/5000475`

**Comment by JPRuskin** [comment]
Do you want any consideration for Core on other platforms? 

It's very easy to do a quick `Start-Process https://mvp.microsoft.com/en-us/PublicProfile/$ID`, but this approach doesn't work reliably on non-Windows platforms.

An example of methods for this is shown within [Trackyon.Utils](https://www.powershellgallery.com/packages/Trackyon.Utils/0.0.2/Content/Internal%5CUtils.ps1) (used in the `Show-Browser` function).

**Comment by lazywinadmin** [comment]
Yep this is what i wanted 👍 ! Thank you James!!
Unfortunately I don't know how to support this in Linux, I opened an entry in #30 to track this
